# Generated by Django 5.2.3 on 2025-06-19 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0004_newsletter_destinataires_planifies'),
    ]

    operations = [
        migrations.AddField(
            model_name='envoi',
            name='log',
            field=models.TextField(blank=True, null=True),
        ),
    ]
